### ISSUE TITLE
Invalidate workspace cache

### ISSUE THREAD

**Issue by markusweigelt** [slub/ocrd_monitor#5]
When a new workspace is added, it is not displayed immediately in list of workspaces.

**Comment by SvenMarcus** [comment]
A simple idea for a custom caching mechanism would be to store the last time the workspaces were indexed and simply update whenever the last modified time of the workspace directory is more recent than that. Thoughts?

**Comment by markusweigelt** [comment]
Would be at least a temporary solution until a database or smarter cache invalidation (without rebuilding the whole cache) is available.

**Comment by markusweigelt** [comment]
Works for me.
